const std = @import("std");

const assert = std.debug.assert;

pub const Id = enum(u8) {
    air,
    stone,
    cobblestone,
    dirt,
    grass,
    plank,
    log,
    gravel,
    sand,
    tnt,
    coal_ore,
    iron_ore,
    gold_ore,
};

front: [2]u16,
back: [2]u16,
north: [2]u16,
south: [2]u16,
east: [2]u16,
west: [2]u16,

pub fn fromId(id: Id) @This() {
    return switch (id) {
        .air => @panic("no texture for air"),
        .stone => .{
            .front = .{ 6, 0 },
            .back = .{ 6, 0 },
            .north = .{ 6, 0 },
            .south = .{ 6, 0 },
            .east = .{ 6, 0 },
            .west = .{ 6, 0 },
        },
        .cobblestone => .{
            .front = .{ 7, 0 },
            .back = .{ 7, 0 },
            .north = .{ 7, 0 },
            .south = .{ 7, 0 },
            .east = .{ 7, 0 },
            .west = .{ 7, 0 },
        },
        .dirt => .{
            .front = .{ 2, 0 },
            .back = .{ 2, 0 },
            .north = .{ 2, 0 },
            .south = .{ 2, 0 },
            .east = .{ 2, 0 },
            .west = .{ 2, 0 },
        },
        .grass => .{
            .front = .{ 1, 0 },
            .back = .{ 1, 0 },
            .north = .{ 0, 0 },
            .south = .{ 2, 0 },
            .east = .{ 1, 0 },
            .west = .{ 1, 0 },
        },
        .plank => .{
            .front = .{ 3, 0 },
            .back = .{ 3, 0 },
            .north = .{ 3, 0 },
            .south = .{ 3, 0 },
            .east = .{ 3, 0 },
            .west = .{ 3, 0 },
        },
        .log => .{
            .front = .{ 4, 0 },
            .back = .{ 4, 0 },
            .north = .{ 5, 0 },
            .south = .{ 5, 0 },
            .east = .{ 4, 0 },
            .west = .{ 4, 0 },
        },
        .gravel => .{
            .front = .{ 13, 0 },
            .back = .{ 13, 0 },
            .north = .{ 13, 0 },
            .south = .{ 13, 0 },
            .east = .{ 13, 0 },
            .west = .{ 13, 0 },
        },
        .sand => .{
            .front = .{ 12, 0 },
            .back = .{ 12, 0 },
            .north = .{ 12, 0 },
            .south = .{ 12, 0 },
            .east = .{ 12, 0 },
            .west = .{ 12, 0 },
        },
        .tnt => .{
            .front = .{ 9, 0 },
            .back = .{ 9, 0 },
            .north = .{ 10, 0 },
            .south = .{ 11, 0 },
            .east = .{ 9, 0 },
            .west = .{ 9, 0 },
        },
        .coal_ore => .{
            .front = .{ 14, 0 },
            .back = .{ 14, 0 },
            .north = .{ 14, 0 },
            .south = .{ 14, 0 },
            .east = .{ 14, 0 },
            .west = .{ 14, 0 },
        },
        .iron_ore => .{
            .front = .{ 15, 0 },
            .back = .{ 15, 0 },
            .north = .{ 15, 0 },
            .south = .{ 15, 0 },
            .east = .{ 15, 0 },
            .west = .{ 15, 0 },
        },
        .gold_ore => .{
            .front = .{ 16, 0 },
            .back = .{ 16, 0 },
            .north = .{ 16, 0 },
            .south = .{ 16, 0 },
            .east = .{ 16, 0 },
            .west = .{ 16, 0 },
        },
    };
}
